name: jakel_base
description: Jakel base package for POS application
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  #fluent_ui: ^3.12.0
  libserialport:
    path: ../libserialport/
  flutter_libserialport:
    path: ../flutter_libserialport/
  dio: ^4.0.6
  get_it: ^7.2.0
  universal_platform: ^1.0.0+1
  window_manager: ^0.3.0
  responsive_builder: ^0.4.2
  bot_toast: ^4.0.2
  easy_localization: ^3.0.1
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  #package_info_plus: ^4.1.0
  rxdart: ^0.27.3
  expandable: ^5.0.1
  syncfusion_flutter_datepicker: ^20.2.40
  dropdown_search: ^5.0.2
  multiple_search_selection: ^2.1.0
  flutter_tags_x: ^1.1.0
  #flutter_datetime_picker: ^1.5.1
  flutter_datetime_picker_plus: ^2.0.1
  uuid: ^3.0.6
  cron: ^0.5.0
  cached_network_image: ^3.2.2
  flutter_svg: ^1.1.6
  #flutter_libserialport: ^0.3.0
  barcode: ^2.2.3
  connectivity_plus: ^3.0.2
  printing: ^5.11.0 # Used for printing receipt
  #flutter_pos_printer_platform: ^1.0.12 # USED  FOR OPENING CASH DRAWER & CUT RECEIPT
  flutter_pos_printer_platform:
    path: ../flutter_pos_printer_platform/
  #esc_pos_utils: ^1.1.0 # USED  FOR OPENING CASH DRAWER & CUT RECEIPT
  esc_pos_utils_plus: ^2.0.2
  platform_device_id: ^1.0.1
  #  new_keyboard_shortcuts: ^0.1.4
  easy_debounce: ^2.0.3
  process_run: ^0.12.5+2
  desktop_multi_window: ^0.2.0
  #keyboard shortcut
  visibility_detector: ^0.3.3
  tuple: ^2.0.1
  #flutter_meedu_videoplayer: ^4.2.26 #video crashing in windows floating display
  flutter_gif: ^0.0.4 #not working in windows
  carousel_slider: ^4.2.1
  async_queue: ^1.3.0
  synchronized: ^3.0.1
  #dart_vlc: ^0.4.0
#  video_player_win: ^2.2.0
#  plugin_platform_interface: ^2.1.4
#  video_player: ^2.5.3
#  video_player_platform_interface: ^6.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  desktop_lifecycle: ^0.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
