name: internal_base
description: Internal base package for internal application
version: 0.0.1
homepage:

environment:
  sdk: ">=2.18.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # A Flutter library to assist with creating and manipulating paths.
  path_drawing: ^1.0.1
  ################## Focus Detector #####################
  #  Similar to onResume()/onPause() on Android and viewDidAppear()/viewDidDisappear() on iOS.
  focus_detector: ^2.0.1
  coupon_uikit: ^0.2.0

  ################## DATA #####################
  # Save data in local cache storage
  shared_preferences: ^2.0.18
  # Network operations
  http: ^0.13.5
  connectivity: ^3.0.6

  ################## BLOC Architecture #####################
  # provides bloc, state, event
  flutter_bloc: ^8.1.2
  # making mandatory params in the object
  meta: ^1.8.0
  # to compare two objects
  equatable: ^2.0.5
  ################## encrypt #####################
  encrypt: ^5.0.1
  #  share: ^2.0.4
  share_plus: ^4.0.10
  ################## barcode #####################
  barcode_widget: ^2.0.3
  pull_to_refresh: ^2.0.0
  # Cache Network Images for faster loading next time
  cached_network_image: ^3.2.0

  ######### webView
  flutter_inappwebview: ^5.7.2+3

  ######### datepicker
  calendar_date_picker2: ^0.5.2
  intl: ^0.17.0
  url_launcher: ^6.1.11

  ########## open camera for barcode
  simple_barcode_scanner: ^0.0.8
  intl_phone_field: ^3.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  desktop_lifecycle: ^0.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:


  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans_Light.ttf
        - asset: assets/fonts/WorkSans_Regular.ttf
        - asset: assets/fonts/WorkSans_Medium.ttf
        - asset: assets/fonts/WorkSans_Semibold.ttf
        - asset: assets/fonts/WorkSans_Bold.ttf
          weight: 700
