import 'package:member_app/data/all_bloc/get_members_details_bloc/repo/member_details.dart';

/// message : "OTP Verified. You can now enjoy the benefits of ARIANI Membership."
/// token : "40489|wu99OsUU73OfTh8CH3905tAt0KBqYKVcYpCLzc8v"
/// status : true
/// member : {"id":229681,"type_details":"","title_details":"","gender_details":"","race_details":"","first_name":"Partha paul","last_name":"","mobile_number":"60176172385","email":"partha.paul007@gmail.com","address_line_1":"","address_line_2":"","city":"","area_code":"","date_of_birth":"2023-05-02","total_orders":0,"spent_till_now":0,"last_purchase_date":"","company_name":"","company_registration_number":"","company_tax_number":"","company_phone":"","notes":"Generated by QR-code on HOUSE OF ARIANI","photo_url":"","available_loyalty_points":0,"membership_id":"","registered_at":"2023-05-03 13:55:32","card_number":"R0DC1881ULOJ","store":"HOUSE OF ARIANI","membership":"","ios_digital_pass_link":"https://retail.ariani.my/download-digital-pass/0fee4dea-f584-11ed-ab86-02001700128e/ios","android_digital_pass_link":"https://retail.ariani.my/download-digital-pass/0fee4dea-f584-11ed-ab86-02001700128e/android","company":{"id":1,"name":"ARIANI TEXTILES & MANUFACTURING (M) SDN. BHD.","code":"AR"}}

class LoginMobileNumberOtpScreenResponse {
  LoginMobileNumberOtpScreenResponse({
    this.message,
    this.token,
    this.status,
    this.member,});

  LoginMobileNumberOtpScreenResponse.fromJson(dynamic json) {
    message = json['message'];
    token = json['token'];
    status = json['status'];
    member = json['member'] != null ? MemberDetails.fromJson(json['member']) : null;
  }
  String? message;
  String? token;
  bool? status;
  MemberDetails? member;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['message'] = message;
    map['token'] = token;
    map['status'] = status;
    if (member != null) {
      map['member'] = member?.toJson();
    }
    return map;
  }

}

// /// id : 229681
// /// type_details : ""
// /// title_details : ""
// /// gender_details : ""
// /// race_details : ""
// /// first_name : "Partha paul"
// /// last_name : ""
// /// mobile_number : "60176172385"
// /// email : "partha.paul007@gmail.com"
// /// address_line_1 : ""
// /// address_line_2 : ""
// /// city : ""
// /// area_code : ""
// /// date_of_birth : "2023-05-02"
// /// total_orders : 0
// /// spent_till_now : 0
// /// last_purchase_date : ""
// /// company_name : ""
// /// company_registration_number : ""
// /// company_tax_number : ""
// /// company_phone : ""
// /// notes : "Generated by QR-code on HOUSE OF ARIANI"
// /// photo_url : ""
// /// available_loyalty_points : 0
// /// membership_id : ""
// /// registered_at : "2023-05-03 13:55:32"
// /// card_number : "R0DC1881ULOJ"
// /// store : "HOUSE OF ARIANI"
// /// membership : ""
// /// ios_digital_pass_link : "https://retail.ariani.my/download-digital-pass/0fee4dea-f584-11ed-ab86-02001700128e/ios"
// /// android_digital_pass_link : "https://retail.ariani.my/download-digital-pass/0fee4dea-f584-11ed-ab86-02001700128e/android"
// /// company : {"id":1,"name":"ARIANI TEXTILES & MANUFACTURING (M) SDN. BHD.","code":"AR"}
//
// class LoginMemberDetails {
//   LoginMemberDetails({
//     this.id,
//     this.typeDetails,
//     this.titleDetails,
//     this.genderDetails,
//     this.raceDetails,
//     this.firstName,
//     this.lastName,
//     this.mobileNumber,
//     this.email,
//     this.addressLine1,
//     this.addressLine2,
//     this.city,
//     this.areaCode,
//     this.dateOfBirth,
//     this.totalOrders,
//     this.spentTillNow,
//     this.lastPurchaseDate,
//     this.companyName,
//     this.companyRegistrationNumber,
//     this.companyTaxNumber,
//     this.companyPhone,
//     this.notes,
//     this.photoUrl,
//     this.availableLoyaltyPoints,
//     this.membershipId,
//     this.registeredAt,
//     this.cardNumber,
//     this.store,
//     this.membership,
//     this.iosDigitalPassLink,
//     this.androidDigitalPassLink,
//     this.company,});
//
//   LoginMemberDetails.fromJson(dynamic json) {
//     id = json['id'];
//
//     typeDetails = json['type_details'] != null ? TypeDetails.fromJson(json['type_details']) : null;
//     titleDetails = json['title_details'] != null ? TitleDetails.fromJson(json['title_details']) : null;
//     genderDetails = json['gender_details'] != null ? GenderDetails.fromJson(json['gender_details']) : null;
//     raceDetails = json['race_details'] != null ? RaceDetails.fromJson(json['race_details']) : null;
//
//
//     firstName = json['first_name'].toString();
//     lastName = json['last_name'].toString();
//     mobileNumber = json['mobile_number'].toString();
//     email = json['email'].toString();
//     addressLine1 = json['address_line_1'].toString();
//     addressLine2 = json['address_line_2'].toString();
//     city = json['city'].toString();
//     areaCode = json['area_code'].toString();
//     dateOfBirth = json['date_of_birth'].toString();
//     totalOrders = json['total_orders'].toString();
//     spentTillNow = json['spent_till_now'].toString();
//     lastPurchaseDate = json['last_purchase_date'].toString();
//     companyName = json['company_name'].toString();
//     companyRegistrationNumber = json['company_registration_number'].toString();
//     companyTaxNumber = json['company_tax_number'].toString();
//     companyPhone = json['company_phone'].toString();
//     notes = json['notes'].toString();
//     photoUrl = json['photo_url'].toString();
//     availableLoyaltyPoints = json['available_loyalty_points'].toString();
//     membershipId = json['membership_id'].toString();
//     registeredAt = json['registered_at'].toString();
//     cardNumber = json['card_number'].toString();
//     store = json['store'].toString();
//     membership = json['membership'].toString();
//     iosDigitalPassLink = json['ios_digital_pass_link'].toString();
//     androidDigitalPassLink = json['android_digital_pass_link'].toString();
//     company = json['company'] != null ? Company.fromJson(json['company']) : null;
//   }
//   int? id;
//   TypeDetails? typeDetails;
//   TitleDetails? titleDetails;
//   GenderDetails? genderDetails;
//   RaceDetails? raceDetails;
//   String? firstName;
//   String? lastName;
//   String? mobileNumber;
//   String? email;
//   String? addressLine1;
//   String? addressLine2;
//   String? city;
//   String? areaCode;
//   String? dateOfBirth;
//   String? totalOrders;
//   String? spentTillNow;
//   String? lastPurchaseDate;
//   String? companyName;
//   String? companyRegistrationNumber;
//   String? companyTaxNumber;
//   String? companyPhone;
//   String? notes;
//   String? photoUrl;
//   String? availableLoyaltyPoints;
//   String? membershipId;
//   String? registeredAt;
//   String? cardNumber;
//   String? store;
//   String? membership;
//   String? iosDigitalPassLink;
//   String? androidDigitalPassLink;
//   Company? company;
//
//   Map<String, dynamic> toJson() {
//     final map = <String, dynamic>{};
//     map['id'] = id;
//     map['type_details'] = typeDetails;
//     map['title_details'] = titleDetails;
//     map['gender_details'] = genderDetails;
//     map['race_details'] = raceDetails;
//     map['first_name'] = firstName;
//     map['last_name'] = lastName;
//     map['mobile_number'] = mobileNumber;
//     map['email'] = email;
//     map['address_line_1'] = addressLine1;
//     map['address_line_2'] = addressLine2;
//     map['city'] = city;
//     map['area_code'] = areaCode;
//     map['date_of_birth'] = dateOfBirth;
//     map['total_orders'] = totalOrders;
//     map['spent_till_now'] = spentTillNow;
//     map['last_purchase_date'] = lastPurchaseDate;
//     map['company_name'] = companyName;
//     map['company_registration_number'] = companyRegistrationNumber;
//     map['company_tax_number'] = companyTaxNumber;
//     map['company_phone'] = companyPhone;
//     map['notes'] = notes;
//     map['photo_url'] = photoUrl;
//     map['available_loyalty_points'] = availableLoyaltyPoints;
//     map['membership_id'] = membershipId;
//     map['registered_at'] = registeredAt;
//     map['card_number'] = cardNumber;
//     map['store'] = store;
//     map['membership'] = membership;
//     map['ios_digital_pass_link'] = iosDigitalPassLink;
//     map['android_digital_pass_link'] = androidDigitalPassLink;
//     if (company != null) {
//       map['company'] = company?.toJson();
//     }
//     return map;
//   }
//
// }

/// id : 1
/// name : "ARIANI TEXTILES & MANUFACTURING (M) SDN. BHD."
/// code : "AR"

class Company {
  Company({
    this.id,
    this.name,
    this.code,});

  Company.fromJson(dynamic json) {
    id = json['id'];
    name = json['name'];
    code = json['code'].toString();
  }
  int? id;
  String? name;
  String? code;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['id'] = id;
    map['name'] = name;
    map['code'] = code;
    return map;
  }

}


/// id : 1
/// name : "Malay"
/// key : "MALAY"

class RaceDetails {
  RaceDetails({
    this.id,
    this.name,
    this.key,});

  RaceDetails.fromJson(dynamic json) {
    id = json['id'];
    name = json['name'];
    key = json['key'];
  }
  int? id;
  String? name;
  String? key;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['id'] = id;
    map['name'] = name;
    map['key'] = key;
    return map;
  }

}

/// id : 2
/// name : "Female"
/// key : "FEMALE"

class GenderDetails {
  GenderDetails({
    this.id,
    this.name,
    this.key,});

  GenderDetails.fromJson(dynamic json) {
    id = json['id'];
    name = json['name'];
    key = json['key'];
  }
  int? id;
  String? name;
  String? key;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['id'] = id;
    map['name'] = name;
    map['key'] = key;
    return map;
  }

}

/// id : 9
/// name : "Mrs"
/// key : "MRS"

class TitleDetails {
  TitleDetails({
    this.id,
    this.name,
    this.key,});

  TitleDetails.fromJson(dynamic json) {
    id = json['id'];
    name = json['name'];
    key = json['key'];
  }
  int? id;
  String? name;
  String? key;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['id'] = id;
    map['name'] = name;
    map['key'] = key;
    return map;
  }

}

/// id : 2
/// name : "Regular"
/// key : "REGULAR"

class TypeDetails {
  TypeDetails({
    this.id,
    this.name,
    this.key,});

  TypeDetails.fromJson(dynamic json) {
    id = json['id'];
    name = json['name'];
    key = json['key'];
  }
  int? id;
  String? name;
  String? key;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['id'] = id;
    map['name'] = name;
    map['key'] = key;
    return map;
  }

}